emptyUPscreen = "test-emptyUsernameAndPassword.png"
emptyPscreen = "test_emptyPassword.png"
lockedScreen = "test_lockedOut.png"
wrongScreen = "test_wrongUser.png"
xbuttonScreen = "test_xButton.png"
loginScreen = "test_loggingIn.png"